name: PR_checks

on:
  pull_request:
    branches:
      - 'master'

env:
  BASE_API_URL: ${{ secrets.BASE_API_URL }}
  RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
  RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
  RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

jobs:

  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}

      - name: Detekt
        run: ./gradlew detekt

  dependency_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}

      - name: Dependency Check Analyze
        run: ./gradlew dependencyCheckAnalyze

  android_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}

      - name: Download secret files repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.SECRET_FILES_GIT_REPOSITORY }}
          token: ${{ secrets.SECRET_FILES_GIT_ACCESS_TOKEN }}
          path: app

      - name: Android Lint
        run: ./gradlew lint

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}

      - name: Download secret files repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.SECRET_FILES_GIT_REPOSITORY }}
          token: ${{ secrets.SECRET_FILES_GIT_ACCESS_TOKEN }}
          path: app

      - name: Unit tests
        run: ./gradlew test

      - name: Create Tests Coverage report
        run: ./gradlew jacocoTestReport

      - name: Upload Tests Coverage report
        run: bash <(curl -s https://codecov.io/bash) -f features/game/storage_impl/build/coverage-report -F moduleA

  build_release_apk:
    needs: [ detekt, android_lint, unit_tests, dependency_check ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}

      - name: Download secret files repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.SECRET_FILES_GIT_REPOSITORY }}
          token: ${{ secrets.SECRET_FILES_GIT_ACCESS_TOKEN }}
          path: app

      - name: Build Release APK
        run: ./gradlew assembleRelease

  build_staging_apk:
    needs: [ detekt, android_lint, unit_tests, dependency_check ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}

      - name: Download secret files repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.SECRET_FILES_GIT_REPOSITORY }}
          token: ${{ secrets.SECRET_FILES_GIT_ACCESS_TOKEN }}
          path: app

      - name: Build Staging APK
        run: ./gradlew assembleStaging