name: PR_checks

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

env:
  BASE_API_URL: ${{ secrets.BASE_API_URL }}
  RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
  RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
  RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

jobs:

  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.11}

      - name: Detekt
        run: ./gradlew detekt

  diktat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.11}

      - name: Diktat
        run: ./gradlew diktatCheck

  dependency_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.11}

      - name: Dependency Check Analyze
        run: ./gradlew dependencyCheckAnalyze

  license_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.11}

      - name: Dependency licenses check
        run: ./gradlew  app:licensee

  android_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.11}

      - name: Download secret files repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.SECRET_FILES_GIT_REPOSITORY }}
          token: ${{ secrets.SECRET_FILES_GIT_ACCESS_TOKEN }}
          path: app

      - name: Android Lint
        run: ./gradlew lint

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.11}

      - name: Download secret files repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.SECRET_FILES_GIT_REPOSITORY }}
          token: ${{ secrets.SECRET_FILES_GIT_ACCESS_TOKEN }}
          path: app

      - name: Unit tests
        run: ./gradlew test

  build_release_apk:
    needs: [ detekt, diktat, android_lint, unit_tests, dependency_check, license_check ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.11}

      - name: Download secret files repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.SECRET_FILES_GIT_REPOSITORY }}
          token: ${{ secrets.SECRET_FILES_GIT_ACCESS_TOKEN }}
          path: app

      - name: Build Release APK
        run: ./gradlew assembleRelease

  build_staging_apk:
    needs: [ detekt, diktat, android_lint, unit_tests, dependency_check, license_check ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.11}

      - name: Download secret files repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.SECRET_FILES_GIT_REPOSITORY }}
          token: ${{ secrets.SECRET_FILES_GIT_ACCESS_TOKEN }}
          path: app

      - name: Build Staging APK
        run: ./gradlew assembleStaging