name: PR_checks

on:
  pull_request:
    branches:
      - 'master'

env:
  BASE_API_URL: ${{ secrets.BASE_API_URL }}
  RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
  RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
  RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

jobs:

  all_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}

      - name: Detekt
        run: ./gradlew detekt

      - name: Dependency Check Analyze
        run: ./gradlew dependencyCheckAnalyze

      - name: Download secret files repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.SECRET_FILES_GIT_REPOSITORY }}
          token: ${{ secrets.SECRET_FILES_GIT_ACCESS_TOKEN }}
          path: app

      - name: Android Lint
        run: ./gradlew lint

      - name: Unit tests
          run: ./gradlew test

      - name: Build Release APK
          run: ./gradlew assembleRelease

      - name: Build Staging APK
        run: ./gradlew assembleStaging