name: PR_checks

on:
  pull_request:
    branches:
      - 'master'

jobs:

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}

      - name: Download secret files repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.SECRET_FILES_GIT_REPOSITORY }}
          token: ${{ secrets.SECRET_FILES_GIT_ACCESS_TOKEN }}
          path: app

      - name: Unit tests
        run: ./gradlew test

      - name: Create Tests Coverage report
        run: ./gradlew jacocoTestReport

      - name: Upload Tests Coverage report
        run: bash <(curl -s https://codecov.io/bash) -f features/game/storage_impl/build/coverage-report/test_coverage.csv -F moduleA