name: PR_checks

on:
  pull_request:
    branches:
      - 'master'

env:
  BASE_API_URL: ${{ secrets.BASE_API_URL }}
  RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
  RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
  RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

jobs:

  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Detekt
        run: ./gradlew detekt -XX:+UseParallelGC

  android_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Android Lint
        run: ./gradlew lint -XX:+UseParallelGC

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Unit tests
        run: ./gradlew test -XX:+UseParallelGC

  download_secret_files:
    needs: [ detekt, android_lint, unit_tests ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download secret files repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.SECRET_FILES_GIT_REPOSITORY }}
          token: ${{ secrets.SECRET_FILES_GIT_ACCESS_TOKEN }}
          path: app

  build_release_apk:
    needs: [ detekt, android_lint, unit_tests, download_secret_files ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Release APK
        run: ./gradlew assembleRelease -XX:+UseParallelGC

  build_staging_apk:
    needs: [ detekt, android_lint, unit_tests, download_secret_files ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Release APK
        run: ./gradlew assembleStaging -XX:+UseParallelGC